new: финальный проект 18 спринта: диплом без фич
Aloizzza/java-explore-with-me pull request #2
Opened 2023-01-06 19:05 UTC by Aloizzza

2023-01-08 19:21 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-01-08 19:21 UTC, FanaticFiz commented on main_service/src/main/java/ru/practicum/compilation/service/CompilationService.java
> +    List<CompilationDto> getAll(Boolean pinned, PageRequest pageRequest);
Используй интерфейс `Pageable pageable` вместо класса `PageRequest`

2023-01-08 19:21 UTC, FanaticFiz commented on main_service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +            throw new BadRequestException("compilation title must not be null");
А где же валидация?
Почему приходится после контроллера, который не должен был пропустить такое, перепроверять?

2023-01-08 19:21 UTC, FanaticFiz commented on main_service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +        eventDto.setConfirmedRequests(participationRepository.countParticipationByEventIdAndStatus(eventDto.getId(),
Неудачный перенос... вынеси действие на отдельную строку

```
    private ShortEventDto setConfirmedRequests(ShortEventDto eventDto) {
        eventDto.setConfirmedRequests(
                participationRepository.countParticipationByEventIdAndStatus(eventDto.getId(), CONFIRMED));

        return eventDto;
    }
```

2023-01-08 19:21 UTC, FanaticFiz commented on main_service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        List<State> stateList = states == null ? null : states
`states == null ? null` бессмысленно же!
Да и инициализировать списки нужно пустым списком а не `null`!

```
        List<State> stateList = new ArrayList<>();
        if (states != null) {
            stateList = states.stream()
                              .map(State::valueOf)
                              .collect(Collectors.toList());
        }
```

2023-01-08 19:21 UTC, FanaticFiz commented on main_service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +                .filter(event -> rangeStart != null ?
Если код в люмбде не короткий и понятный то он должен быть вынесен в метод...
Смотреть/читать/воспринимать это не возможно!

2023-01-08 19:21 UTC, FanaticFiz commented on main_service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +            events = events.stream().filter(shortEventDto ->
- Каждая новая операция с новой строки!
- .get() нельзя брать без проверки!

2023-01-08 19:21 UTC, FanaticFiz commented on stats_service/src/main/java/ru/practicum/hit/controller/HitController.java
> +    @GetMapping("stats")
Нет `/` -> '/stats'

Да и как то я не увидел чтобы это использовалось, почему?
Разве не надо для event выбирать статистику?

2023-01-09 16:49 UTC, Aloizzza commented on main_service/src/main/java/ru/practicum/compilation/service/CompilationService.java
> +    List<CompilationDto> getAll(Boolean pinned, PageRequest pageRequest);
О, врубилась. Pageable это интерфейс, как List

2023-01-09 17:36 UTC, Aloizzza commented on main_service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +            throw new BadRequestException("compilation title must not be null");
Не работало, несмотря на все аннотации. Сейчас удалила - работает...

2023-01-09 21:13 UTC, Aloizzza commented on stats_service/src/main/java/ru/practicum/hit/controller/HitController.java
> +    @GetMapping("stats")
Занятно, с Постманом работает как со слешем так и без)) да, используется для Event. В двух тестах используется: https://github.com/yandex-praktikum/java-explore-with-me/tree/develop/postman

2023-01-10 19:04 UTC, FanaticFiz commented on main_service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +            throw new BadRequestException("compilation title must not be null");
Магия? ))

2023-01-10 19:12 UTC, FanaticFiz approved these changes

2023-01-11 00:44 UTC, Aloizzza commented on main_service/src/main/java/ru/practicum/participation/service/ParticipationServiceImpl.java
> +/*        if (userId == null || eventId == null) {
Как ты это находишь??? И задваивание кусочков кода

2023-01-11 11:26 UTC, merged